/* Generated by scripts/generate-themes.mjs. Do not edit. */
export const THEME_BOOTSTRAP_REGISTRY = {
  "exawatt-air-light": {
    "appearance": "light",
    "background": "#F3F5F2",
    "foreground": "#18211D",
    "signal": "#087F6E",
    "colorScheme": "light",
    "material": {
      "tint": "#F7FAF6",
      "opacity": 0.78,
      "blur": 24,
      "saturation": 1.1,
      "fallback": "#F7FAF6"
    }
  },
  "exawatt-classic-dark": {
    "appearance": "dark",
    "background": "#04060B",
    "foreground": "#DCEBFF",
    "signal": "#19E6FF",
    "colorScheme": "dark",
    "material": {
      "tint": "#070B14",
      "opacity": 0.94,
      "blur": 18,
      "saturation": 1.05,
      "fallback": "#070B14"
    }
  },
  "exawatt-night-dark": {
    "appearance": "dark",
    "background": "#0B100E",
    "foreground": "#E8F0EB",
    "signal": "#60BFA7",
    "colorScheme": "dark",
    "material": {
      "tint": "#0D1511",
      "opacity": 0.88,
      "blur": 22,
      "saturation": 1.04,
      "fallback": "#0D1511"
    }
  }
} as const;

export type ThemeBootstrapId = keyof typeof THEME_BOOTSTRAP_REGISTRY;
