/**
 * Real delivery-queue state captured from this repository's own
 * `<git-common-dir>/exawatt-delivery/` on 2026-10-05 (ENG-017 S16). Nothing
 * here is sensitive: ticket files and metrics events carry shas, branch
 * names, check ids and timings. The reader's tests parse these exact shapes
 * so a change in what `agent:land` writes fails here, not on the lens.
 *
 * Generated by a script over the live state; edit the script's selection,
 * not the JSON, when a new shape needs covering.
 */

/** Integrated, docs lane, one commit, no rebase. */
export const TICKET_INTEGRATED_DOCS = {
  "schemaVersion": 1,
  "id": "00000579-2f73fc40",
  "number": 579,
  "revision": 6,
  "status": "integrated",
  "branch": "docs/agent/polish-attention",
  "lane": "docs",
  "baseSha": "f926154f3a8c97689bacb86ec6938e41f2340299",
  "candidateSha": "fe255b13b1d97fccd37aef311555d003b9d96b8f",
  "attemptSha": "fe255b13b1d97fccd37aef311555d003b9d96b8f",
  "attemptRef": "refs/heads/agent-attempts/docs-agent-polish-attention-1791173085691-1-f04549fe",
  "attemptRefs": [
    "refs/heads/agent-attempts/docs-agent-polish-attention-1791173085691-1-f04549fe"
  ],
  "attemptNumber": 1,
  "changedPaths": [
    "docs/engineering/roadmap.md"
  ],
  "checks": [
    {
      "id": "recipe-renderers",
      "phase": "candidate",
      "lane": "docs",
      "status": "passed",
      "durationMs": 5120,
      "completedAt": "2026-10-05T04:04:45.493Z"
    },
    {
      "id": "open-source:paths:check",
      "phase": "candidate",
      "lane": "docs",
      "status": "passed",
      "durationMs": 1253,
      "completedAt": "2026-10-05T04:04:45.508Z"
    },
    {
      "id": "content:scan",
      "phase": "candidate",
      "lane": "docs",
      "status": "passed",
      "durationMs": 249,
      "completedAt": "2026-10-05T04:04:45.519Z"
    },
    {
      "id": "roadmap-contract",
      "phase": "candidate",
      "lane": "docs",
      "status": "passed",
      "durationMs": 623,
      "completedAt": "2026-10-05T04:04:45.531Z"
    }
  ],
  "dogfood": false,
  "owner": {
    "pid": 90488,
    "token": "563afe8b-66d7-4b1c-bac9-ed069c6d149f",
    "epoch": 1,
    "heartbeatAt": "2026-10-05T04:05:00.097Z"
  },
  "admittedAt": "2026-10-05T04:04:46.926Z",
  "updatedAt": "2026-10-05T04:05:00.097Z",
  "terminalAt": "2026-10-05T04:05:00.097Z",
  "result": {
    "integratedSha": "fe255b13b1d97fccd37aef311555d003b9d96b8f",
    "lockHoldMs": 12220,
    "exactFloorSha": "fe255b13b1d97fccd37aef311555d003b9d96b8f",
    "queueWaitMs": 78,
    "publicState": "published",
    "publicSha": "9511b7f459577ca480cf9cc61f30031fd269c7a6"
  },
  "headAt": "2026-10-05T04:04:47.004Z"
} as const;

/** Integrated, worktree lane, five commits (`fix(...)` subjects, oldest names the item). */
export const TICKET_INTEGRATED_WORKTREE = {
  "schemaVersion": 1,
  "id": "00000577-3007f290",
  "number": 577,
  "revision": 9,
  "status": "integrated",
  "branch": "agent/polish-attention",
  "lane": "worktree",
  "baseSha": "08465d517211a44c6965d65f88134e8a1e56e3a3",
  "candidateSha": "19712d6ff5b032586aee5a8fe9f45e3cc3be9c44",
  "attemptSha": "19712d6ff5b032586aee5a8fe9f45e3cc3be9c44",
  "attemptRef": "refs/heads/agent-attempts/polish-attention-1791172777701-1-477d6308",
  "attemptRefs": [
    "refs/heads/agent-attempts/polish-attention-1791172777701-1-477d6308"
  ],
  "attemptNumber": 1,
  "changedPaths": [
    "docs/engineering/architecture.md",
    "docs/engineering/decisions/0032-restore-project-scoped-session-recovery.md",
    "docs/engineering/decisions/0046-reading-does-not-resolve-attention.md",
    "docs/engineering/design-system.md",
    "docs/engineering/incidents/0034-fleet-return-rebuilds-hidden-terminals.md",
    "docs/engineering/incidents/0036-native-focus-predates-attention-subscription.md",
    "docs/engineering/incidents/README.md",
    "docs/engineering/projects/daily-driver-adoption.md",
    "docs/engineering/projects/delegation-visibility.md",
    "docs/engineering/projects/design-system-of-record.md",
    "docs/engineering/projects/deterministic-session-rehydration.md",
    "docs/engineering/projects/objective-engine.md",
    "docs/engineering/projects/spatial-operations-board.md",
    "docs/engineering/projects/stellar-small-fleet.md",
    "docs/engineering/roadmap.md",
    "docs/product/concepts.md",
    "docs/product/guides/getting-started.md",
    "docs/product/marketing.md",
    "docs/product/reference/agent-state.md",
    "docs/product/reference/session-lifecycle.md",
    "electron/main/device-power.test.ts",
    "electron/main/device-power.ts",
    "electron/main/harness-events/codex-app-server.test.ts",
    "electron/main/harness-events/codex-app-server.ts",
    "electron/main/harness-events/codex-turn-observation.test.ts",
    "electron/main/harness-events/codex-turn-observation.ts",
    "electron/main/harness-events/delegation-monitor.ts",
    "electron/main/harness-events/delegation-state.ts",
    "electron/main/harness-events/turn-truth.test.ts",
    "electron/main/harness-events/turn-truth.ts",
    "electron/main/ipc-arguments.test.ts",
    "electron/main/ipc-arguments.ts",
    "electron/main/native-window-focus.test.ts",
    "electron/main/native-window-focus.ts",
    "electron/main/notification-policy.test.ts",
    "electron/main/notification-policy.ts",
    "electron/main/permissions/native-notification.test.ts",
    "electron/main/preload.ts",
    "electron/main/pty-ipc.ts",
    "electron/main/pty/attention-monitor.test.ts",
    "electron/main/pty/attention-monitor.ts",
    "electron/main/pty/attention-session-id.test.ts",
    "electron/main/pty/attention-session-id.ts",
    "electron/main/pty/closed-session-ledger.test.ts",
    "electron/main/pty/closed-session-ledger.ts",
    "electron/main/pty/initial-attention.test.ts",
    "electron/main/pty/initial-attention.ts",
    "electron/main/pty/session-manager.ts",
    "electron/main/pty/session-operation.test.ts",
    "electron/main/roadmap/attention-observations.test.ts",
    "electron/main/roadmap/attention-observations.ts",
    "electron/main/roadmap/roadmap-ipc.ts",
    "electron/main/shutdown-coordinator.test.ts",
    "electron/main/shutdown-coordinator.ts",
    "electron/main/workspace-store.test.ts",
    "electron/main/workspace-store.ts",
    "package.json",
    "packages/core/src/__tests__/agent-source-ids.test.ts",
    "packages/core/src/__tests__/demo-workspace-transport.test.ts",
    "packages/core/src/__tests__/local-sessions.test.ts",
    "packages/core/src/__tests__/roadmap-attention.test.ts",
    "packages/core/src/__tests__/session-attention.test.ts",
    "packages/core/src/agent-sources.ts",
    "packages/core/src/desktop-bridge/api.ts",
    "packages/core/src/desktop-bridge/channels.ts",
    "packages/core/src/desktop-bridge/index.ts",
    "packages/core/src/desktop-bridge/pty.ts",
    "packages/core/src/desktop-bridge/roadmap.ts",
    "packages/core/src/index.ts",
    "packages/core/src/roadmap/attention.ts",
    "packages/core/src/session-attention.ts",
    "packages/core/src/session-record-extensions.ts",
    "packages/core/src/transports/demo-workspace.ts",
    "packages/core/src/transports/local-sessions.ts",
    "packages/core/src/types/agent.ts",
    "packages/ui-model/src/index.ts",
    "packages/ui-model/src/roadmap-attention.test.ts",
    "packages/ui-model/src/roadmap-attention.ts",
    "packages/ui-model/src/session-attention-copy.ts",
    "packages/ui-model/src/session-display-copy.ts",
    "packages/ui-model/src/spatial-board.test.ts",
    "packages/ui-model/src/spatial-board.ts",
    "scripts/delivery-policy.test.mjs",
    "scripts/electron-delegation-eval.mjs",
    "scripts/electron-device-power-eval.mjs",
    "scripts/electron-exact-resume-eval.mjs",
    "scripts/electron-fleet-attention-eval.mjs",
    "scripts/electron-rehydration-idempotency-eval.mjs",
    "scripts/electron-session-lifecycle-eval.mjs",
    "scripts/electron-session-spatial-parity-eval.mjs",
    "scripts/electron-source-compatibility-eval.mjs",
    "scripts/electron-turn-truth-eval.mjs",
    "scripts/electron-workspace-tenancy-eval.mjs",
    "scripts/exact-public-recertification.test.mjs",
    "scripts/landing-dev-server.test.mjs",
    "scripts/lib/delivery-policy.mjs",
    "scripts/lib/landing-dev-server.mjs",
    "scripts/roadmap-rail-eval.mjs",
    "scripts/spatial-attention-eval.mjs",
    "scripts/workspace-chrome-layout-eval.mjs",
    "src/app/eval/session-unread/page.tsx",
    "src/components/fleet/spatial/operations-board/operations-board-agent-layer.tsx",
    "src/components/fleet/spatial/operations-board/operations-board-controls.tsx",
    "src/components/fleet/spatial/operations-board/operations-board-materials.ts",
    "src/components/fleet/spatial/operations-board/operations-board-status-marks.tsx",
    "src/components/fleet/spatial/spatial-fleet-client.tsx",
    "src/components/fleet/spatial/use-fleet-attention.dom.test.tsx",
    "src/components/fleet/spatial/use-fleet-attention.ts",
    "src/components/nav/update-ready-notice.tsx",
    "src/components/roadmap/use-fleet-roadmap-attention.test.tsx",
    "src/components/roadmap/use-fleet-roadmap-attention.ts",
    "src/components/shortcuts/command-palette-default.test.tsx",
    "src/components/shortcuts/command-palette.tsx",
    "src/components/shortcuts/shortcut-provider.tsx",
    "src/components/status-light/inspection.ts",
    "src/components/workspace/expose-overlay.test.tsx",
    "src/components/workspace/expose-overlay.tsx",
    "src/components/workspace/harness-icons.tsx",
    "src/components/workspace/harnesses.ts",
    "src/components/workspace/live-session-model-control.tsx",
    "src/components/workspace/paused-agent-record.test.tsx",
    "src/components/workspace/paused-agent-record.tsx",
    "src/components/workspace/resume-recovery-bar.test.tsx",
    "src/components/workspace/resume-recovery-bar.tsx",
    "src/components/workspace/roadmap-lens-input.ts",
    "src/components/workspace/session-clone.ts",
    "src/components/workspace/session-display-copy.test.ts",
    "src/components/workspace/session-display-copy.ts",
    "src/components/workspace/session-lifecycle-vocabulary.test.tsx",
    "src/components/workspace/session-overview-card.tsx",
    "src/components/workspace/session-restore-panel.test.tsx",
    "src/components/workspace/session-restore-panel.tsx",
    "src/components/workspace/session-status.test.ts",
    "src/components/workspace/session-status.ts",
    "src/components/workspace/session-switcher-identity.tsx",
    "src/components/workspace/session-unread-marker.tsx",
    "src/components/workspace/split-layout.ts",
    "src/components/workspace/status-glyphs.tsx",
    "src/components/workspace/switcher-rows.test.ts",
    "src/components/workspace/switcher-rows.ts",
    "src/components/workspace/tab-strip.test.tsx",
    "src/components/workspace/tab-strip.tsx",
    "src/components/workspace/turn-truth-pipeline.test.ts",
    "src/components/workspace/use-workspace-state.ts",
    "src/components/workspace/workspace-client.tsx",
    "src/components/workspace/workspace-state/layout-restore.test.ts",
    "src/components/workspace/workspace-state/layout-restore.ts",
    "src/components/workspace/workspace-state/layout-serialize.test.ts",
    "src/components/workspace/workspace-state/layout-serialize.ts",
    "src/components/workspace/workspace-state/persisted-layout.ts",
    "src/components/workspace/workspace-state/session-record-extensions.ts",
    "src/components/workspace/workspace-state/source-compatibility.test.ts",
    "src/components/workspace/workspace-state/use-attention-focus.test.tsx",
    "src/components/workspace/workspace-state/use-attention-focus.ts",
    "src/components/workspace/workspace-state/use-recently-closed.ts",
    "src/components/workspace/workspace-state/use-session-launch.ts",
    "src/components/workspace/workspace-state/use-session-runtime.ts",
    "src/components/workspace/workspace-state/use-workspace-hydration.ts",
    "src/components/workspace/workspace-state/use-workspace-persistence.ts",
    "src/components/workspace/workspace-state/workspace-model.test.ts",
    "src/components/workspace/workspace-state/workspace-model.ts",
    "src/components/workspace/workspace-storage-recovery.test.tsx",
    "src/lib/architecture/manifest.ts",
    "src/lib/demo-workspace/demo-workspace-client.test.tsx",
    "src/lib/demo-workspace/demo-workspace-client.tsx",
    "src/lib/demo-workspace/model.ts",
    "src/lib/fleet/fleet-provider.tsx",
    "src/lib/fleet/local-workspace-sessions.test.ts",
    "src/lib/fleet/local-workspace-sessions.ts",
    "src/lib/fleet/session-attention-source.dom.test.tsx"
  ],
  "checks": [
    {
      "id": "open-source:paths:check",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 1262,
      "completedAt": "2026-10-05T03:42:35.510Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "content:scan",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 436,
      "completedAt": "2026-10-05T03:42:35.961Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "lint",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 28868,
      "completedAt": "2026-10-05T03:43:04.843Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "type-check",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 6413,
      "completedAt": "2026-10-05T03:43:11.272Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "test:agent-delivery",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 94520,
      "completedAt": "2026-10-05T03:44:45.808Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "exports:check",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 5065,
      "completedAt": "2026-10-05T03:44:50.888Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "vitest-related",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 41770,
      "completedAt": "2026-10-05T03:45:32.671Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "copy:check",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 759,
      "completedAt": "2026-10-05T03:45:33.445Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "theme:check",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 743,
      "completedAt": "2026-10-05T03:45:34.203Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "stale-async-ratchet",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 1003,
      "completedAt": "2026-10-05T03:45:35.221Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "verify:community-build",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 15978,
      "completedAt": "2026-10-05T03:45:51.214Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "verify:community-runtime",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 1129,
      "completedAt": "2026-10-05T03:45:52.359Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "electron:compile",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 4338,
      "completedAt": "2026-10-05T03:45:56.711Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:r3f",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 24168,
      "completedAt": "2026-10-05T03:46:25.173Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "roadmap-contract",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 606,
      "completedAt": "2026-10-05T03:46:25.795Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:spatial:attention",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 22726,
      "completedAt": "2026-10-05T03:46:48.709Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:electron:source-compatibility",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 10758,
      "completedAt": "2026-10-05T03:46:59.674Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:electron:device-power",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 20980,
      "completedAt": "2026-10-05T03:47:20.839Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:electron:permissions",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 15693,
      "completedAt": "2026-10-05T03:47:36.724Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:electron:source-power",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 21667,
      "completedAt": "2026-10-05T03:47:58.585Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:electron:project-pause",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 11777,
      "completedAt": "2026-10-05T03:48:10.559Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:electron:clone-context",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 10394,
      "completedAt": "2026-10-05T03:48:21.143Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:electron:model-change",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 11333,
      "completedAt": "2026-10-05T03:48:32.669Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:workspace:ribbon:bench",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 16321,
      "completedAt": "2026-10-05T03:48:49.186Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:workspace:chrome",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 17547,
      "completedAt": "2026-10-05T03:49:06.907Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:workspace:split",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 2592,
      "completedAt": "2026-10-05T03:49:09.675Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:workspace:paused",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 2605,
      "completedAt": "2026-10-05T03:49:12.464Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:workspace:team",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 8642,
      "completedAt": "2026-10-05T03:49:21.288Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:navigation:spine",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 26508,
      "completedAt": "2026-10-05T03:49:47.985Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:spatial:viewport",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 6971,
      "completedAt": "2026-10-05T03:49:55.160Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:electron:connected-fleet",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 44194,
      "completedAt": "2026-10-05T03:50:39.369Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:electron:project-agent",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 76743,
      "completedAt": "2026-10-05T03:51:56.317Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:roadmap:rail",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 53608,
      "completedAt": "2026-10-05T03:52:50.132Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:electron:recents",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 11517,
      "completedAt": "2026-10-05T03:53:01.842Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:electron:lifecycle",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 39464,
      "completedAt": "2026-10-05T03:53:41.502Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:electron:idempotency",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 23135,
      "completedAt": "2026-10-05T03:54:04.856Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:spatial",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 56975,
      "completedAt": "2026-10-05T03:55:02.024Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:spatial:emergence",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 25553,
      "completedAt": "2026-10-05T03:55:27.811Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:spatial:pointer",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 16471,
      "completedAt": "2026-10-05T03:55:44.485Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:electron:delegation",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 41356,
      "completedAt": "2026-10-05T03:56:26.048Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:electron:turn-truth",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 52183,
      "completedAt": "2026-10-05T03:57:18.444Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:electron:tenancy",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 33248,
      "completedAt": "2026-10-05T03:57:51.887Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:navigation:electron",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 19774,
      "completedAt": "2026-10-05T03:58:11.855Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:electron:resume",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 40934,
      "completedAt": "2026-10-05T03:58:52.987Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:electron:chrome",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 18666,
      "completedAt": "2026-10-05T03:59:11.847Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    },
    {
      "id": "eval:electron:session-parity",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 25560,
      "completedAt": "2026-10-05T03:59:37.624Z",
      "slotMode": "acquired",
      "slotWaitMs": 0
    }
  ],
  "dogfood": true,
  "owner": {
    "pid": 31094,
    "token": "9ad5b0c7-d5dc-4173-9bf3-5815aab3f34f",
    "epoch": 1,
    "heartbeatAt": "2026-10-05T04:00:06.603Z"
  },
  "admittedAt": "2026-10-05T03:59:40.211Z",
  "updatedAt": "2026-10-05T04:00:06.603Z",
  "terminalAt": "2026-10-05T04:00:06.603Z",
  "result": {
    "integratedSha": "19712d6ff5b032586aee5a8fe9f45e3cc3be9c44",
    "lockHoldMs": 25361,
    "exactFloorSha": "19712d6ff5b032586aee5a8fe9f45e3cc3be9c44",
    "queueWaitMs": 76,
    "publicState": "published",
    "publicSha": "3e4e9392ff108ba96f31a17de73d571689ac15bb"
  },
  "headAt": "2026-10-05T03:59:40.287Z"
} as const;

/** Failed at the head after a rebase whose dev-server refresh did not come back. */
export const TICKET_FAILED_REBASE = {
  "schemaVersion": 1,
  "id": "00000574-fed099b0",
  "number": 574,
  "revision": 40,
  "status": "failed",
  "branch": "agent/fleet-v39-choice",
  "lane": "worktree",
  "baseSha": "8265ec1c20cb9e8301746c6ec1f27922d218be38",
  "candidateSha": "07349fd0a9147453cafc3e834d491ec5ae37764e",
  "attemptSha": "07349fd0a9147453cafc3e834d491ec5ae37764e",
  "attemptRef": "refs/heads/agent-attempts/fleet-v39-choice-1791170289013-1-1d3a3e4e",
  "attemptRefs": [
    "refs/heads/agent-attempts/fleet-v39-choice-1791170289013-1-1d3a3e4e"
  ],
  "attemptNumber": 1,
  "changedPaths": [
    "ASSET_PROVENANCE.json",
    "docs/engineering/projects/demo-arc-execution.md",
    "docs/engineering/projects/spatial-operations-board.md",
    "docs/engineering/roadmap.md",
    "packages/ui-model/src/spatial-board.test.ts",
    "packages/ui-model/src/spatial-board.ts",
    "public/images/hero-board-poster.jpg",
    "src/app/hud-gallery/board-study/page.tsx",
    "src/components/fleet/spatial/operations-board/operations-board-agent-layer.tsx",
    "src/components/fleet/spatial/operations-board/operations-board-canvas.tsx",
    "src/components/fleet/spatial/operations-board/operations-board-controls.tsx",
    "src/components/fleet/spatial/operations-board/operations-board-presentation.test.ts",
    "src/components/fleet/spatial/operations-board/operations-board-presentation.ts",
    "src/components/fleet/spatial/operations-board/operations-board-surface.tsx",
    "src/components/fleet/spatial/operations-board/operations-board-theme.test.tsx",
    "src/components/fleet/spatial/operations-board/operations-board-zone-layer.tsx",
    "src/components/site/hero-board/capture.ts"
  ],
  "checks": [
    {
      "id": "open-source:paths:check",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 1337,
      "completedAt": "2026-10-05T03:09:48.652Z",
      "slotMode": "acquired",
      "slotWaitMs": 1
    },
    {
      "id": "content:scan",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 296,
      "completedAt": "2026-10-05T03:09:48.967Z",
      "slotMode": "acquired",
      "slotWaitMs": 1
    },
    {
      "id": "lint",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 30823,
      "completedAt": "2026-10-05T03:10:19.834Z",
      "slotMode": "acquired",
      "slotWaitMs": 1
    },
    {
      "id": "type-check",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 7459,
      "completedAt": "2026-10-05T03:10:27.312Z",
      "slotMode": "acquired",
      "slotWaitMs": 1
    },
    {
      "id": "test:agent-delivery",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 106974,
      "completedAt": "2026-10-05T03:12:14.305Z",
      "slotMode": "acquired",
      "slotWaitMs": 1
    },
    {
      "id": "exports:check",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 407,
      "completedAt": "2026-10-05T03:12:14.730Z",
      "slotMode": "acquired",
      "slotWaitMs": 1
    },
    {
      "id": "vitest-related",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 18876,
      "completedAt": "2026-10-05T03:12:33.622Z",
      "slotMode": "acquired",
      "slotWaitMs": 1
    },
    {
      "id": "copy:check",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 815,
      "completedAt": "2026-10-05T03:12:34.453Z",
      "slotMode": "acquired",
      "slotWaitMs": 1
    },
    {
      "id": "theme:check",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 807,
      "completedAt": "2026-10-05T03:12:35.276Z",
      "slotMode": "acquired",
      "slotWaitMs": 1
    },
    {
      "id": "stale-async-ratchet",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 1098,
      "completedAt": "2026-10-05T03:12:36.392Z",
      "slotMode": "acquired",
      "slotWaitMs": 1
    },
    {
      "id": "verify:community-build",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 24214,
      "completedAt": "2026-10-05T03:13:00.622Z",
      "slotMode": "acquired",
      "slotWaitMs": 1
    },
    {
      "id": "verify:community-runtime",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 1275,
      "completedAt": "2026-10-05T03:13:01.914Z",
      "slotMode": "acquired",
      "slotWaitMs": 1
    },
    {
      "id": "eval:r3f",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 20966,
      "completedAt": "2026-10-05T03:13:23.368Z",
      "slotMode": "acquired",
      "slotWaitMs": 1
    },
    {
      "id": "roadmap-contract",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 810,
      "completedAt": "2026-10-05T03:13:24.198Z",
      "slotMode": "acquired",
      "slotWaitMs": 1
    },
    {
      "id": "eval:spatial:viewport",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 7063,
      "completedAt": "2026-10-05T03:13:31.518Z",
      "slotMode": "acquired",
      "slotWaitMs": 1
    },
    {
      "id": "eval:hero-board",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 44808,
      "completedAt": "2026-10-05T03:14:16.571Z",
      "slotMode": "acquired",
      "slotWaitMs": 1
    },
    {
      "id": "eval:spatial",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 57147,
      "completedAt": "2026-10-05T03:15:13.964Z",
      "slotMode": "acquired",
      "slotWaitMs": 1
    },
    {
      "id": "eval:spatial:emergence",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 25646,
      "completedAt": "2026-10-05T03:15:39.873Z",
      "slotMode": "acquired",
      "slotWaitMs": 1
    },
    {
      "id": "eval:spatial:pointer",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 16581,
      "completedAt": "2026-10-05T03:15:56.691Z",
      "slotMode": "acquired",
      "slotWaitMs": 1
    },
    {
      "id": "eval:navigation:electron",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 72153,
      "completedAt": "2026-10-05T03:17:09.078Z",
      "slotMode": "acquired",
      "slotWaitMs": 1
    },
    {
      "id": "eval:electron:session-parity",
      "phase": "candidate",
      "status": "passed",
      "durationMs": 59589,
      "completedAt": "2026-10-05T03:18:08.938Z",
      "slotMode": "acquired",
      "slotWaitMs": 1
    }
  ],
  "dogfood": false,
  "owner": {
    "pid": 75204,
    "token": "e839f065-b6b3-42aa-9084-51fec4907d05",
    "epoch": 1,
    "heartbeatAt": "2026-10-05T03:21:12.372Z"
  },
  "admittedAt": "2026-10-05T03:18:10.712Z",
  "updatedAt": "2026-10-05T03:21:12.372Z",
  "terminalAt": "2026-10-05T03:21:12.372Z",
  "result": {
    "reason": "the dev server at http://localhost:7460 did not come back after the rebase refresh: ENOTEMPTY: directory not empty, rmdir '/Users/fixture/Code/Personal/FullVibeAI/exawatt-v39/.next/dev'. Its log is /Users/fixture/Code/Personal/FullVibeAI/exawatt-v39/.next/landing-dev-server.log. eval:r3f did not run.",
    "preservedAttemptRef": "refs/heads/agent-attempts/fleet-v39-choice-1791170289013-1-1d3a3e4e"
  },
  "headAt": "2026-10-05T03:18:10.840Z"
} as const;

/** Rebase-phase floor checks the head recorded for TICKET_FAILED_REBASE. */
export const METRICS_REBASE_CHECKS = [
  {
    "schemaVersion": 1,
    "type": "floor_check",
    "at": "2026-10-05T03:21:10.452Z",
    "ticketId": "00000574-fed099b0",
    "candidateSha": "08465d517211a44c6965d65f88134e8a1e56e3a3",
    "id": "verify:community-build",
    "phase": "rebase",
    "status": "passed",
    "durationMs": 11023,
    "completedAt": "2026-10-05T03:21:10.435Z",
    "slotMode": "acquired",
    "slotWaitMs": 0
  },
  {
    "schemaVersion": 1,
    "type": "floor_check",
    "at": "2026-10-05T03:21:11.807Z",
    "ticketId": "00000574-fed099b0",
    "candidateSha": "08465d517211a44c6965d65f88134e8a1e56e3a3",
    "id": "verify:community-runtime",
    "phase": "rebase",
    "status": "passed",
    "durationMs": 1338,
    "completedAt": "2026-10-05T03:21:11.790Z",
    "slotMode": "acquired",
    "slotWaitMs": 0
  }
] as const;

/** Candidate-phase floor checks for a landing whose first check failed (no ticket ever followed). */
export const METRICS_CANDIDATE_FAILED = [
  {
    "schemaVersion": 1,
    "type": "floor_check",
    "at": "2026-10-05T04:04:20.522Z",
    "candidateSha": "1e420426932747cdad9a051f741b76d2fc45d67a",
    "id": "recipe-renderers",
    "phase": "candidate",
    "lane": "docs",
    "status": "failed",
    "durationMs": 5135,
    "completedAt": "2026-10-05T04:04:20.508Z"
  },
  {
    "schemaVersion": 1,
    "type": "floor_check",
    "at": "2026-10-05T04:04:20.534Z",
    "candidateSha": "1e420426932747cdad9a051f741b76d2fc45d67a",
    "id": "open-source:paths:check",
    "phase": "candidate",
    "lane": "docs",
    "status": "passed",
    "durationMs": 1267,
    "completedAt": "2026-10-05T04:04:20.522Z"
  },
  {
    "schemaVersion": 1,
    "type": "floor_check",
    "at": "2026-10-05T04:04:20.546Z",
    "candidateSha": "1e420426932747cdad9a051f741b76d2fc45d67a",
    "id": "content:scan",
    "phase": "candidate",
    "lane": "docs",
    "status": "passed",
    "durationMs": 253,
    "completedAt": "2026-10-05T04:04:20.534Z"
  },
  {
    "schemaVersion": 1,
    "type": "floor_check",
    "at": "2026-10-05T04:04:20.557Z",
    "candidateSha": "1e420426932747cdad9a051f741b76d2fc45d67a",
    "id": "roadmap-contract",
    "phase": "candidate",
    "lane": "docs",
    "status": "passed",
    "durationMs": 632,
    "completedAt": "2026-10-05T04:04:20.546Z"
  }
] as const;

/** Candidate-phase floor checks that all passed; TICKET_INTEGRATED_DOCS was admitted right after. */
export const METRICS_CANDIDATE_PASSED = [
  {
    "schemaVersion": 1,
    "type": "floor_check",
    "at": "2026-10-05T04:04:45.507Z",
    "candidateSha": "fe255b13b1d97fccd37aef311555d003b9d96b8f",
    "id": "recipe-renderers",
    "phase": "candidate",
    "lane": "docs",
    "status": "passed",
    "durationMs": 5120,
    "completedAt": "2026-10-05T04:04:45.493Z"
  },
  {
    "schemaVersion": 1,
    "type": "floor_check",
    "at": "2026-10-05T04:04:45.519Z",
    "candidateSha": "fe255b13b1d97fccd37aef311555d003b9d96b8f",
    "id": "open-source:paths:check",
    "phase": "candidate",
    "lane": "docs",
    "status": "passed",
    "durationMs": 1253,
    "completedAt": "2026-10-05T04:04:45.508Z"
  },
  {
    "schemaVersion": 1,
    "type": "floor_check",
    "at": "2026-10-05T04:04:45.531Z",
    "candidateSha": "fe255b13b1d97fccd37aef311555d003b9d96b8f",
    "id": "content:scan",
    "phase": "candidate",
    "lane": "docs",
    "status": "passed",
    "durationMs": 249,
    "completedAt": "2026-10-05T04:04:45.519Z"
  },
  {
    "schemaVersion": 1,
    "type": "floor_check",
    "at": "2026-10-05T04:04:45.542Z",
    "candidateSha": "fe255b13b1d97fccd37aef311555d003b9d96b8f",
    "id": "roadmap-contract",
    "phase": "candidate",
    "lane": "docs",
    "status": "passed",
    "durationMs": 623,
    "completedAt": "2026-10-05T04:04:45.531Z"
  }
] as const;

export const METRICS_ADMITTED = [
  {
    "schemaVersion": 1,
    "type": "queue_admitted",
    "at": "2026-10-05T04:04:46.943Z",
    "ticketId": "00000579-2f73fc40",
    "ticketNumber": 579,
    "candidateSha": "fe255b13b1d97fccd37aef311555d003b9d96b8f"
  }
] as const;
export const METRICS_TERMINAL = [
  {
    "schemaVersion": 1,
    "type": "queue_terminal",
    "at": "2026-10-05T04:05:00.109Z",
    "ticketId": "00000579-2f73fc40",
    "ticketNumber": 579,
    "status": "integrated",
    "queueWaitMs": 78,
    "integratedSha": "fe255b13b1d97fccd37aef311555d003b9d96b8f",
    "lockHoldMs": 12220,
    "exactFloorSha": "fe255b13b1d97fccd37aef311555d003b9d96b8f",
    "publicState": "published",
    "publicSha": "9511b7f459577ca480cf9cc61f30031fd269c7a6"
  }
] as const;

/** A candidate-phase conflict probe: that landing never reached the queue. */
export const METRICS_PROBE_CONFLICT = [
  {
    "schemaVersion": 1,
    "type": "probe_conflict",
    "at": "2026-09-29T05:49:51.468Z",
    "phase": "candidate",
    "candidateSha": "63586c38d33df984b0b8f9a66fed6f9e92d41898",
    "baseSha": "cd37c9c693ebeff56ad31b1aaab2f1e9276a81ed",
    "commit": "65c87b5e1a94d104a2201e2304d21140e3d223ff",
    "paths": [
      "scripts/lib/delivery-policy.mjs"
    ]
  }
] as const;
