/**
 * Reads the published macOS build from the same feed the installed app
 * updates from (decision 0009). The download page must never advertise a
 * version that `electron-updater` would not also see.
 *
 * `latest-mac.yml` is machine-generated by electron-builder, so this parses
 * exactly the shape that generator emits rather than pulling a general YAML
 * parser into the runtime dependency set.
 */

export const DESKTOP_UPDATE_CHANNEL_URL =
  'https://numfrucdnnksxbnfftpa.supabase.co/storage/v1/object/public/desktop-updates/macos/arm64';

export interface DesktopBuild {
  version: string;
  /** ISO-8601 publish timestamp from the update feed. */
  releaseDate: string | null;
  /** Direct link to the DMG a human installs. */
  downloadUrl: string;
  fileName: string;
  /** Bytes, when the feed reports them. */
  size: number | null;
}

interface FeedFile {
  url: string;
  size: number | null;
}

export function parseLatestMacFeed(text: string): DesktopBuild | null {
  const version = /^version:\s*(\S+)\s*$/m.exec(text)?.[1];
  if (!version) return null;
  const releaseDate = /^releaseDate:\s*'?([^'\r\n]+?)'?\s*$/m.exec(text)?.[1];

  const files: FeedFile[] = [];
  let insideFiles = false;
  for (const line of text.split(/\r?\n/)) {
    if (/^files:\s*$/.test(line)) {
      insideFiles = true;
      continue;
    }
    if (!insideFiles) continue;
    // Any unindented key ends the sequence.
    if (line.trim() && !/^\s/.test(line)) break;
    const url = /^\s*-\s+url:\s*'?([^'\s]+)'?\s*$/.exec(line);
    if (url) {
      files.push({ url: url[1], size: null });
      continue;
    }
    const size = /^\s*size:\s*(\d+)\s*$/.exec(line);
    if (size && files.length > 0) {
      files[files.length - 1].size = Number(size[1]);
    }
  }

  // The DMG is what a person installs; the zip in the same feed is the
  // updater's payload format and would confuse an invitee.
  const dmg = files.find(file => file.url.endsWith('.dmg'));
  if (!dmg) return null;

  return {
    version,
    releaseDate: releaseDate ?? null,
    fileName: dmg.url,
    downloadUrl: `${DESKTOP_UPDATE_CHANNEL_URL}/${encodeURIComponent(dmg.url)}`,
    size: dmg.size,
  };
}

export async function fetchDesktopBuild(
  fetchImpl: typeof fetch = fetch
): Promise<DesktopBuild | null> {
  try {
    const response = await fetchImpl(
      `${DESKTOP_UPDATE_CHANNEL_URL}/latest-mac.yml`,
      { signal: AbortSignal.timeout(8_000), cache: 'no-store' }
    );
    if (!response.ok) return null;
    return parseLatestMacFeed(await response.text());
  } catch {
    return null;
  }
}

export function formatBuildSize(bytes: number | null): string | null {
  if (!bytes || bytes <= 0) return null;
  if (bytes < 1_000_000_000) return `${Math.round(bytes / 1_000_000)} MB`;
  return `${(bytes / 1_000_000_000).toFixed(2)} GB`;
}

export function formatReleaseDate(value: string | null): string | null {
  if (!value) return null;
  const parsed = Date.parse(value);
  if (!Number.isFinite(parsed)) return null;
  return new Intl.DateTimeFormat('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    timeZone: 'UTC',
  }).format(parsed);
}
