import { existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { POPULATION_STATUS_ORDER } from '@/components/fleet/spatial/operations-board/population-dots';
import { buildHeroBoardCapture } from './capture-source';
import { HERO_STATUS_ORDER } from './capture-types';

const CAPTURE_PATH = join(import.meta.dirname, 'capture.ts');

function serialize(capture: ReturnType<typeof buildHeroBoardCapture>): string {
  const zones = capture.zones
    .map(zone => `  ${JSON.stringify(zone)},`)
    .join('\n');
  const units = capture.units
    .map(unit => `  ${JSON.stringify(unit)},`)
    .join('\n');
  const delegations = capture.delegations
    .map(child => `  ${JSON.stringify(child)},`)
    .join('\n');
  return `/**
 * GENERATED by \`capture.test.ts\` from the Demo Workspace (ENG-031 W2).
 * Do not hand-edit: run \`HERO_CAPTURE_WRITE=1 pnpm vitest run src/components/site/hero-board/capture.test.ts\`.
 * One record per line, held there by \`prettier-ignore\`, so a regenerated
 * capture diffs as the rows that actually moved.
 *
 * One real capture of the Demo Workspace at the Fleet altitude, frozen so the
 * marketing hero never ships the demo fixture. It is demo data and its scale
 * tier is synthetic; \`source.stamp\` travels with it and is printed inside the
 * hero frame.
 */
import type {
  HeroBoardCapture,
  HeroBoardDelegation,
  HeroBoardUnit,
  HeroBoardZone,
} from './capture-types';

// prettier-ignore
const ZONES: HeroBoardZone[] = [
${zones}
];

// prettier-ignore
const UNITS: HeroBoardUnit[] = [
${units}
];

// prettier-ignore
const DELEGATIONS: HeroBoardDelegation[] = [
${delegations}
];

// prettier-ignore
export const HERO_BOARD_CAPTURE: HeroBoardCapture = {
  version: 1,
  source: ${JSON.stringify(capture.source)},
  bounds: ${JSON.stringify(capture.bounds)},
  counts: ${JSON.stringify(capture.counts)},
  zones: ZONES,
  units: UNITS,
  delegations: DELEGATIONS,
};
`;
}

describe('hero board capture', () => {
  it('keeps the ordinal contract with the production board', () => {
    expect([...HERO_STATUS_ORDER]).toEqual([...POPULATION_STATUS_ORDER]);
  });

  it('matches the Demo Workspace board model', async () => {
    const capture = buildHeroBoardCapture();
    if (process.env.HERO_CAPTURE_WRITE === '1') {
      writeFileSync(CAPTURE_PATH, serialize(capture), 'utf8');
    }
    expect(existsSync(CAPTURE_PATH)).toBe(true);
    const { HERO_BOARD_CAPTURE } = await import('./capture');
    expect(HERO_BOARD_CAPTURE).toEqual(capture);
  });

  it('is a bounded, honest capture', () => {
    const capture = buildHeroBoardCapture();
    expect(capture.source.demo).toBe(true);
    expect(capture.source.synthetic).toBe(true);
    expect(capture.units.length).toBeGreaterThan(120);
    expect(capture.units.length).toBeLessThanOrEqual(260);
    expect(capture.zones.length).toBeGreaterThan(4);
    expect(capture.counts.needsYou).toBeGreaterThan(0);
    for (const unit of capture.units) {
      expect(Number.isFinite(unit.x)).toBe(true);
      expect(Number.isFinite(unit.y)).toBe(true);
      expect(unit.size).toBeGreaterThan(0);
      expect(unit.status).toBeGreaterThanOrEqual(0);
      expect(unit.status).toBeLessThan(HERO_STATUS_ORDER.length);
    }
  });

  it('carries real delegated runs, with their lineage and their census', () => {
    const capture = buildHeroBoardCapture();
    // The delegation beat is REAL product state (ENG-023 D3c, ENG-004 V3.4),
    // not a motion graphic authored for the site. If the fixture ever stops
    // delegating, the panel that says "agents run agents" has to stop too.
    expect(capture.delegations.length).toBeGreaterThan(0);
    expect(capture.counts.delegating).toBeGreaterThan(0);
    expect(capture.counts.delegated).toBeGreaterThanOrEqual(
      capture.delegations.length
    );
    for (const child of capture.delegations) {
      const parent = capture.units[child.parent];
      expect(parent).toBeDefined();
      // Same family, smaller: the established ratio, never a new shape.
      expect(child.size).toBeGreaterThan(0);
      expect(child.size).toBeLessThan(parent!.size);
      // The tether starts at the parent and ends at the child, so lineage
      // cannot render backwards.
      expect(
        Math.hypot(child.tether.x1 - parent!.x, child.tether.y1 - parent!.y)
      ).toBeLessThan(
        Math.hypot(child.tether.x1 - child.x, child.tether.y1 - child.y) + 1e-6
      );
      expect(child.overflow >= 0).toBe(true);
      if (child.overflow > 0) expect(child.type).toBeNull();
      else expect((child.type ?? '').trim().length).toBeGreaterThan(0);
    }
  });

  it('names every unit and every Project, so the board can explain itself', () => {
    const capture = buildHeroBoardCapture();
    // The operator's verdict on the unlabelled board was "a pile of rotating
    // icons". A unit without a real name and a real contract line cannot be
    // hovered into an identity, so the capture is the place that guarantees it.
    for (const unit of capture.units) {
      expect(unit.name.trim().length).toBeGreaterThan(0);
      expect(unit.doing.trim().length).toBeGreaterThan(0);
    }
    expect(new Set(capture.units.map(unit => unit.name)).size).toBe(
      capture.units.length
    );
    // Every Project circle carries its needs-you count, and the parts sum to
    // the whole the hero prints.
    const needsYou = capture.zones.reduce(
      (sum, zone) => sum + zone.needsYou,
      0
    );
    expect(needsYou).toBe(capture.counts.needsYou);
    for (const zone of capture.zones) {
      expect(zone.label.trim().length).toBeGreaterThan(0);
      expect(zone.needsYou).toBeLessThanOrEqual(zone.agentCount);
    }
  });
});
