import { readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  parseThemeDefinition,
  validateThemeChannels,
  validateThemeContrast,
} from '../themes/contract.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const THEME_DIR = path.join(ROOT, 'themes', 'v1');
const CHECK = process.argv.includes('--check');

const EXPECTED = {
  'exawatt-classic-dark': { appearance: 'dark', availability: 'production' },
  'exawatt-air-light': { appearance: 'light', availability: 'production' },
  'exawatt-night-dark': { appearance: 'dark', availability: 'production' },
};

function formatIssue(issue) {
  const role = issue.path.length ? issue.path.join('.') : 'theme';
  return `${role}: ${issue.message}`;
}

async function loadThemes() {
  const files = (await readdir(THEME_DIR))
    .filter(file => file.endsWith('.json'))
    .sort();
  const themes = [];
  const errors = [];
  for (const file of files) {
    const absolute = path.join(THEME_DIR, file);
    let value;
    try {
      value = JSON.parse(await readFile(absolute, 'utf8'));
    } catch (error) {
      errors.push(`${file}: ${error instanceof Error ? error.message : error}`);
      continue;
    }
    try {
      const theme = parseThemeDefinition(value);
      if (`${theme.id}.json` !== file) {
        errors.push(`${file}: filename must match id ${theme.id}`);
      }
      for (const contrastError of validateThemeContrast(theme)) {
        errors.push(`${file}: ${contrastError}`);
      }
      for (const channelError of validateThemeChannels(theme)) {
        errors.push(`${file}: ${channelError}`);
      }
      themes.push(theme);
    } catch (error) {
      if (error && typeof error === 'object' && 'issues' in error) {
        for (const issue of error.issues) {
          errors.push(`${file}: ${formatIssue(issue)}`);
        }
      } else {
        errors.push(`${file}: ${error instanceof Error ? error.message : error}`);
      }
    }
  }

  const ids = new Set();
  for (const theme of themes) {
    if (ids.has(theme.id)) errors.push(`${theme.id}: duplicate stable ID`);
    ids.add(theme.id);
    const expected = EXPECTED[theme.id];
    if (!expected) {
      errors.push(`${theme.id}: V1 only permits the three approved built-ins`);
      continue;
    }
    if (theme.appearance !== expected.appearance) {
      errors.push(
        `${theme.id}.appearance: expected ${expected.appearance}, received ${theme.appearance}`
      );
    }
    if (theme.availability !== expected.availability) {
      errors.push(
        `${theme.id}.availability: expected ${expected.availability}, received ${theme.availability}`
      );
    }
  }
  for (const id of Object.keys(EXPECTED)) {
    if (!ids.has(id)) errors.push(`${id}: approved built-in definition is missing`);
  }

  if (errors.length) {
    throw new Error(`Theme validation failed:\n- ${errors.join('\n- ')}`);
  }
  return themes.sort((left, right) => left.id.localeCompare(right.id));
}

function kebab(value) {
  return value.replace(/[A-Z]/g, character => `-${character.toLowerCase()}`);
}

function flatten(value, pathParts = []) {
  return Object.entries(value).flatMap(([key, child]) => {
    const nextPath = [...pathParts, kebab(key)];
    if (child && typeof child === 'object' && !Array.isArray(child)) {
      return flatten(child, nextPath);
    }
    return [[nextPath.join('-'), child]];
  });
}

function generateCss(themes) {
  const groups = [
    'foundation',
    'hud',
    'status',
    'consumption',
    'readiness',
    'terminal',
    'spatial',
    'typography',
    'material',
    'bootstrap',
  ];
  const blocks = themes.map(theme => {
    const values = Object.fromEntries(groups.map(group => [group, theme[group]]));
    const declarations = flatten(values)
      .map(([role, value]) => {
        const cssValue = role.startsWith('material-') && role.endsWith('-blur')
          ? `${value}px`
          : value;
        return `  --exa-${role}: ${cssValue};`;
      })
      .join('\n');
    return `[data-exa-theme='${theme.id}'] {\n  color-scheme: ${theme.appearance};\n${declarations}\n}`;
  });
  return `/* Generated by scripts/generate-themes.mjs. Do not edit. */\n\n${blocks.join('\n\n')}\n`;
}

function generateRegistry(themes) {
  const entries = themes
    .map(
      (theme, index) =>
        `  '${theme.id}': THEME_DEFINITIONS[${index}],`
    )
    .join('\n');
  const productionIds = themes
    .filter(theme => theme.availability === 'production')
    .map(theme => `'${theme.id}'`)
    .join(', ');
  const galleryIds = themes
    .filter(theme => theme.availability === 'gallery')
    .map(theme => `'${theme.id}'`)
    .join(', ');
  return `/* Generated by scripts/generate-themes.mjs. Do not edit. */\nimport type { ThemeDefinitionV1, ThemeRegistry } from '@/lib/appearance/types';\n\nexport const THEME_DEFINITIONS = ${JSON.stringify(themes, null, 2)} as const satisfies readonly ThemeDefinitionV1[];\n\nexport const THEME_REGISTRY = {\n${entries}\n} as const satisfies ThemeRegistry;\n\nexport type BuiltInThemeId = keyof typeof THEME_REGISTRY;\nexport const PRODUCTION_THEME_IDS = [${productionIds}] as const;\nexport const GALLERY_THEME_IDS = [${galleryIds}] as const;\n`;
}

function generateElectronBootstrap(themes) {
  const bootstrap = Object.fromEntries(
    themes.map(theme => [
      theme.id,
      {
        appearance: theme.appearance,
        availability: theme.availability,
        ...theme.bootstrap,
        muted: theme.foundation.textMuted,
        faint: theme.foundation.border,
        danger: theme.foundation.destructive,
        material: theme.material.chrome,
      },
    ])
  );
  return `/* Generated by scripts/generate-themes.mjs. Do not edit. */\nexport const THEME_BOOTSTRAP_REGISTRY = ${JSON.stringify(bootstrap, null, 2)} as const;\n\nexport type ThemeBootstrapId = keyof typeof THEME_BOOTSTRAP_REGISTRY;\n`;
}

async function emit(relativePath, content) {
  const absolute = path.join(ROOT, relativePath);
  if (CHECK) {
    let current = '';
    try {
      current = await readFile(absolute, 'utf8');
    } catch {
      // The comparison below emits the actionable error.
    }
    if (current !== content) {
      throw new Error(
        `${relativePath} is stale; run pnpm theme:generate and commit the result`
      );
    }
    return;
  }
  await writeFile(absolute, content, 'utf8');
  process.stdout.write(`[theme-generate] wrote ${relativePath}\n`);
}

const themes = await loadThemes();
await emit('src/generated/themes.css', generateCss(themes));
await emit('src/generated/theme-registry.ts', generateRegistry(themes));
await emit(
  'electron/main/generated-theme-bootstrap.ts',
  generateElectronBootstrap(themes)
);
if (CHECK) {
  process.stdout.write(`[theme-check] ${themes.length} themes valid and generated artifacts current\n`);
}
