/**
 * The base-tier demo fleet (ENG-027 W3): 27 hand-authored Agents across
 * Voltaic's ten Projects. This is the tier an operator reads UP CLOSE —
 * every name, goal, subtitle, blocker, and fault is written to survive a
 * shoulder-read.
 *
 * Status spread is deliberate, so the fleet exercises the whole five-signal
 * status-light protocol (ENG-016 D40) rather than reading uniformly idle:
 *
 *   working 9 + reviewing 3  → active
 *   idle 5                   → off
 *   complete 5               → result
 *   blocked 3                → needs-you (approval, question, credential —
 *                              the three operator-answerable `BlockerType`
 *                              stories; the union's `error`/`awaiting_agent`
 *                              members surface through fault notes and
 *                              delegation states, not authored blockers)
 *   error 2                  → fault
 *
 * Delegation (ENG-023): four Claude Code parents carry eight delegated runs
 * between them. Codex agents never carry children — the source records no
 * delegation (`SOURCE_CAPABILITIES.codex.delegation` is false), and the demo
 * must not fake a record the real source cannot produce.
 *
 * Every non-coding Agent is `readiness: 'preview'` (ENG-026): the research,
 * marketing, and support desks show the Agent Types vision (ENG-028) and
 * must never imply those capabilities ship today.
 */

import type { DemoFleetAgent } from './types';
import { deepFreezeFixture } from './types';
import { DEMO_WORKSPACE_NOW_MS, HOUR_MS, MIN_MS, DAY_MS } from './startup';

const NOW = DEMO_WORKSPACE_NOW_MS;
const m = (n: number) => NOW - n * MIN_MS;
const h = (n: number) => NOW - n * HOUR_MS;
const d = (n: number) => NOW - n * DAY_MS;

export const DEMO_BASE_AGENTS: readonly DemoFleetAgent[] = deepFreezeFixture([
  /* ---------------- dispatch-engine ---------------- */
  {
    id: 'vg-dsp-forecast',
    name: 'Forecast refit shadow run',
    projectKey: 'dispatch-engine',
    goal: 'Run the refit LMP forecaster in shadow against production bidding and score day six of ten.',
    contextLabel: 'Scoring shadow-bid day six',
    status: 'working',
    source: 'claude-code',
    model: 'claude-opus-5',
    effort: 'high',
    gitBranch: 'agent/dsp-31-shadow-run',
    roadmapItemId: 'DSP-31',
    link: 'declared',
    startedAtMs: h(5),
    lastActivityAtMs: m(2),
    turns: 16,
    usage: {
      input: 342_000,
      cacheRead: 27_800_000,
      cacheWrite: 2_640_000,
      output: 428_000,
      webSearches: 3,
    },
    delegated: [
      {
        agentId: 'agent-4e12',
        agentType: 'Explore',
        model: 'claude-sonnet-5',
        task: 'Sweep basis-feature candidate set',
        startedAtMs: h(4),
        usage: { input: 118_000, cacheRead: 4_100_000, cacheWrite: 420_000, output: 156_000 },
      },
      {
        agentId: 'agent-4e2b',
        agentType: 'general-purpose',
        model: 'claude-opus-5',
        task: 'Score harness against holdout week',
        startedAtMs: h(2),
        usage: { input: 96_000, cacheRead: 3_300_000, cacheWrite: 360_000, output: 141_000 },
      },
    ],
    readiness: 'live',
    tier: 'base',
    initiativeId: 'init-ercot',
  },
  {
    id: 'vg-dsp-bidrails',
    name: 'Bid rail replay divergence',
    projectKey: 'dispatch-engine',
    goal: 'Prototype monotonicity checks for bid curves and replay them over the fixture market days.',
    contextLabel: 'Replay diverged on day seven',
    status: 'error',
    source: 'codex',
    model: 'gpt-5.3-codex',
    effort: 'high',
    gitBranch: 'agent/dsp-32-bid-rails',
    roadmapItemId: 'DSP-32',
    link: 'branch',
    startedAtMs: h(7),
    lastActivityAtMs: m(41),
    turns: 11,
    usage: {
      input: 128_000,
      cacheRead: 6_400_000,
      cacheWrite: 660_000,
      output: 352_000,
      reasoning: 251_000,
    },
    delegated: [],
    faultNote:
      'Backtest replay exited 1: fixture day seven produced a non-monotone curve the new rail rejected — the fixture predates the ORDC adder feature.',
    readiness: 'live',
    tier: 'base',
    initiativeId: 'init-ercot',
  },
  {
    id: 'vg-dsp-holdout',
    name: 'Holdout eval rerun',
    projectKey: 'dispatch-engine',
    goal: 'Re-run the holdout-week evaluation with the corrected settlement data and publish the MAE table.',
    contextLabel: 'MAE table ready for review',
    status: 'complete',
    source: 'codex',
    model: 'gpt-5.3-codex',
    effort: 'medium',
    gitBranch: null,
    roadmapItemId: 'DSP-31',
    link: 'title',
    startedAtMs: h(9),
    lastActivityAtMs: h(3),
    turns: 8,
    usage: {
      input: 74_000,
      cacheRead: 3_400_000,
      cacheWrite: 380_000,
      output: 208_000,
      reasoning: 149_000,
    },
    delegated: [],
    readiness: 'live',
    tier: 'base',
    initiativeId: 'init-ercot',
  },
  {
    id: 'vg-dsp-ancillary',
    name: 'Ancillary co-opt sketch',
    projectKey: 'dispatch-engine',
    goal: 'Sketch the joint energy-plus-reserves optimization and estimate revenue lift on pilot data.',
    contextLabel: 'Reviewing revenue lift estimate',
    status: 'reviewing',
    source: 'claude-code',
    model: 'claude-opus-5',
    effort: 'high',
    gitBranch: 'agent/dsp-33-co-opt',
    roadmapItemId: 'DSP-33',
    link: 'declared',
    startedAtMs: h(26),
    lastActivityAtMs: m(24),
    turns: 13,
    usage: {
      input: 214_000,
      cacheRead: 17_900_000,
      cacheWrite: 1_720_000,
      output: 284_000,
      webSearches: 5,
    },
    delegated: [],
    readiness: 'live',
    tier: 'base',
    initiativeId: 'init-ercot',
  },

  /* ---------------- grid-api ---------------- */
  {
    id: 'vg-api-signing',
    name: 'Webhook signing cutover',
    projectKey: 'grid-api',
    goal: 'Move the last three sandbox partners to v2 signature verification and prepare the shared-secret retirement.',
    contextLabel: 'Migrating final sandbox partners',
    status: 'working',
    source: 'codex',
    model: 'gpt-5.3-codex',
    effort: 'medium',
    gitBranch: null,
    roadmapItemId: 'API-18',
    link: 'declared',
    startedAtMs: h(3),
    lastActivityAtMs: m(6),
    turns: 10,
    usage: {
      input: 92_000,
      cacheRead: 4_300_000,
      cacheWrite: 470_000,
      output: 246_000,
      reasoning: 178_000,
    },
    delegated: [],
    readiness: 'live',
    tier: 'base',
    initiativeId: 'init-home-ga',
  },
  {
    id: 'vg-api-verifylib',
    name: 'Verification library docs',
    projectKey: 'grid-api',
    goal: 'Write the partner-facing signature verification guide with runnable examples in three languages.',
    contextLabel: 'Guide drafted, examples verified',
    status: 'complete',
    source: 'claude-code',
    model: 'claude-sonnet-5',
    effort: 'medium',
    gitBranch: 'agent/api-18-verify-docs',
    roadmapItemId: 'API-18',
    link: 'branch',
    startedAtMs: h(29),
    lastActivityAtMs: h(22),
    turns: 7,
    usage: {
      input: 56_000,
      cacheRead: 2_600_000,
      cacheWrite: 300_000,
      output: 88_000,
      webSearches: 4,
    },
    delegated: [],
    readiness: 'live',
    tier: 'base',
    initiativeId: 'init-home-ga',
  },
  {
    id: 'vg-api-sandbox',
    name: 'Sandbox self-service reset',
    projectKey: 'grid-api',
    goal: 'Build the partner sandbox reset flow so partners stop filing support tickets to clear state.',
    contextLabel: 'Awaiting key rotation approval',
    status: 'blocked',
    source: 'claude-code',
    model: 'claude-opus-5',
    effort: 'medium',
    gitBranch: 'agent/api-19-sandbox-reset',
    roadmapItemId: 'API-19',
    link: 'declared',
    startedAtMs: h(6),
    lastActivityAtMs: h(2),
    turns: 9,
    usage: {
      input: 88_000,
      cacheRead: 5_100_000,
      cacheWrite: 540_000,
      output: 121_000,
    },
    delegated: [],
    blocker: {
      type: 'approval_required',
      title: 'Sandbox reset rotates partner API keys — approve rotation policy?',
      description:
        'Resetting a sandbox invalidates that partner’s existing sandbox keys. The utility program manager has not approved automatic rotation; proceeding without approval breaks two partners mid-integration.',
      suggestedResponses: [
        'Approve automatic rotation',
        'Keep keys, reset data only',
        'Hold for the partner sync on Tuesday',
      ],
      createdAtMs: h(2),
    },
    readiness: 'live',
    tier: 'base',
    initiativeId: 'init-home-ga',
  },

  /* ---------------- voltaic-home ---------------- */
  {
    id: 'vg-home-onboard',
    name: 'Onboarding resumable state',
    projectKey: 'voltaic-home',
    goal: 'Implement resumable enrollment state and abandonment telemetry for the three-screen flow.',
    contextLabel: 'Wiring resumable enrollment state',
    status: 'working',
    source: 'claude-code',
    model: 'claude-opus-5',
    effort: 'high',
    gitBranch: 'agent/home-24-resumable',
    roadmapItemId: 'HOME-24',
    link: 'declared',
    startedAtMs: h(4),
    lastActivityAtMs: m(1),
    turns: 15,
    usage: {
      input: 296_000,
      cacheRead: 24_100_000,
      cacheWrite: 2_310_000,
      output: 372_000,
      webSearches: 2,
    },
    delegated: [
      {
        agentId: 'agent-9a01',
        agentType: 'Explore',
        model: 'claude-sonnet-5',
        task: 'Map current enrollment state writes',
        startedAtMs: h(3.5),
        usage: { input: 84_000, cacheRead: 2_900_000, cacheWrite: 310_000, output: 112_000 },
      },
      {
        agentId: 'agent-9a17',
        agentType: 'general-purpose',
        model: 'claude-opus-5',
        task: 'Abandonment telemetry event schema',
        startedAtMs: h(2.2),
        usage: { input: 61_000, cacheRead: 2_100_000, cacheWrite: 240_000, output: 94_000 },
      },
      {
        agentId: 'agent-9a2c',
        agentType: 'fork',
        model: 'claude-opus-5',
        task: 'Resume-token expiry edge cases',
        startedAtMs: h(1.1),
        usage: { input: 47_000, cacheRead: 1_600_000, cacheWrite: 190_000, output: 71_000 },
      },
    ],
    readiness: 'live',
    tier: 'base',
    initiativeId: 'init-home-ga',
  },
  {
    id: 'vg-home-transparency',
    name: 'Dispatch transparency spike',
    projectKey: 'voltaic-home',
    goal: 'Prototype the dispatch-event transparency screen: when the battery ran, why, and what it earned.',
    contextLabel: 'Reviewing event timeline prototype',
    status: 'reviewing',
    source: 'claude-code',
    model: 'claude-sonnet-5',
    effort: 'medium',
    gitBranch: 'agent/home-25-transparency',
    roadmapItemId: 'HOME-25',
    link: 'declared',
    startedAtMs: h(23),
    lastActivityAtMs: h(1),
    turns: 11,
    usage: {
      input: 132_000,
      cacheRead: 8_900_000,
      cacheWrite: 940_000,
      output: 178_000,
    },
    delegated: [],
    readiness: 'live',
    tier: 'base',
    initiativeId: 'init-home-ga',
  },
  {
    id: 'vg-home-pushopt',
    name: 'Push opt-in prompts',
    projectKey: 'voltaic-home',
    goal: 'Move the notification permission prompt to after the first successful dispatch event.',
    contextLabel: 'Queued behind onboarding rebuild',
    status: 'idle',
    source: 'codex',
    model: 'gpt-5.3-codex-mini',
    effort: 'low',
    gitBranch: null,
    roadmapItemId: null,
    link: null,
    startedAtMs: d(1.4),
    lastActivityAtMs: h(19),
    turns: 4,
    usage: {
      input: 21_000,
      cacheRead: 940_000,
      cacheWrite: 110_000,
      output: 58_000,
      reasoning: 39_000,
    },
    delegated: [],
    readiness: 'live',
    tier: 'base',
    initiativeId: null,
  },
  {
    id: 'vg-home-outage',
    name: 'Outage banner soak test',
    projectKey: 'voltaic-home',
    goal: 'Soak-test the outage banner state machine against replayed grid-event telemetry from July.',
    contextLabel: 'Soak passed, zero stuck banners',
    status: 'complete',
    source: 'codex',
    model: 'gpt-5.3-codex',
    effort: 'medium',
    gitBranch: null,
    roadmapItemId: 'HOME-22',
    link: 'title',
    startedAtMs: h(31),
    lastActivityAtMs: h(26),
    turns: 9,
    usage: {
      input: 68_000,
      cacheRead: 3_100_000,
      cacheWrite: 350_000,
      output: 190_000,
      reasoning: 132_000,
    },
    delegated: [],
    readiness: 'live',
    tier: 'base',
    initiativeId: 'init-home-ga',
  },

  /* ---------------- telemetry-ingest ---------------- */
  {
    id: 'vg-tel-dedupe',
    name: 'Idempotent write path',
    projectKey: 'telemetry-ingest',
    goal: 'Make ingest writes idempotent on device id plus vendor sequence so retry storms stop double-counting.',
    contextLabel: 'Testing retry-storm replay',
    status: 'working',
    source: 'codex',
    model: 'gpt-5.3-codex',
    effort: 'high',
    gitBranch: null,
    roadmapItemId: 'TEL-14',
    link: 'declared',
    startedAtMs: h(6),
    lastActivityAtMs: m(9),
    turns: 14,
    usage: {
      input: 156_000,
      cacheRead: 7_600_000,
      cacheWrite: 780_000,
      output: 424_000,
      reasoning: 301_000,
    },
    delegated: [],
    readiness: 'live',
    tier: 'base',
    initiativeId: 'init-pilot-500',
  },
  {
    id: 'vg-tel-drift',
    name: 'Meter drift alerting',
    projectKey: 'telemetry-ingest',
    goal: 'Build drift detection between gateway readings and utility meter data, with alerting.',
    contextLabel: 'Needs drift tolerance decision',
    status: 'blocked',
    source: 'codex',
    model: 'gpt-5.3-codex',
    effort: 'medium',
    gitBranch: null,
    roadmapItemId: 'TEL-15',
    link: 'declared',
    startedAtMs: h(8),
    lastActivityAtMs: h(1),
    turns: 7,
    usage: {
      input: 54_000,
      cacheRead: 2_400_000,
      cacheWrite: 280_000,
      output: 141_000,
      reasoning: 96_000,
    },
    delegated: [],
    blocker: {
      type: 'input_needed',
      title: 'Which drift tolerance should page ops: 0.5% or 2%?',
      description:
        'At 0.5% the July data would have produced 41 alerts (nine real). At 2% it produces 6 alerts (five real, one real miss). Ops has not picked a starting point.',
      suggestedResponses: ['Start at 2%, tighten later', 'Start at 0.5%', 'Page at 2%, log at 0.5%'],
      createdAtMs: h(1),
    },
    readiness: 'live',
    tier: 'base',
    initiativeId: 'init-pilot-500',
  },
  {
    id: 'vg-tel-replay',
    name: 'Replay tool sketch',
    projectKey: 'telemetry-ingest',
    goal: 'Sketch the firehose replay tool: any historical hour, replayed against a candidate pipeline build.',
    contextLabel: 'Parked until dedupe lands',
    status: 'idle',
    source: 'claude-code',
    model: 'claude-sonnet-5',
    effort: 'low',
    gitBranch: 'agent/tel-17-replay-sketch',
    roadmapItemId: 'TEL-17',
    link: 'branch',
    startedAtMs: d(2.1),
    lastActivityAtMs: d(1.8),
    turns: 5,
    usage: {
      input: 34_000,
      cacheRead: 1_500_000,
      cacheWrite: 170_000,
      output: 47_000,
    },
    delegated: [],
    readiness: 'live',
    tier: 'base',
    initiativeId: 'init-pilot-500',
  },

  /* ---------------- edge-gateway ---------------- */
  {
    id: 'vg-edge-ota',
    name: 'Staged rollout halt logic',
    projectKey: 'edge-gateway',
    goal: 'Implement the staged OTA rollout with automatic halt when unit failure rate is elevated.',
    contextLabel: 'Halt thresholds under lab test',
    status: 'working',
    source: 'claude-code',
    model: 'claude-opus-5',
    effort: 'high',
    gitBranch: 'agent/edge-9-staged-rollout',
    roadmapItemId: 'EDGE-9',
    link: 'declared',
    startedAtMs: h(7),
    lastActivityAtMs: m(4),
    turns: 12,
    usage: {
      input: 204_000,
      cacheRead: 16_300_000,
      cacheWrite: 1_580_000,
      output: 262_000,
    },
    delegated: [
      {
        agentId: 'agent-b3d4',
        agentType: 'Explore',
        model: 'claude-sonnet-5',
        task: 'Audit lab-fleet failure telemetry',
        startedAtMs: h(5.5),
        usage: { input: 72_000, cacheRead: 2_500_000, cacheWrite: 270_000, output: 98_000 },
      },
    ],
    readiness: 'live',
    tier: 'base',
    initiativeId: 'init-pilot-500',
  },
  {
    id: 'vg-edge-modbus',
    name: 'Modbus conformance bench',
    projectKey: 'edge-gateway',
    goal: 'Stand up the vendor adapter conformance suite against the lab bench hardware.',
    contextLabel: 'Vendor B adapter timing out',
    status: 'error',
    source: 'codex',
    model: 'gpt-5.3-codex',
    effort: 'medium',
    gitBranch: null,
    roadmapItemId: 'EDGE-10',
    link: 'declared',
    startedAtMs: h(11),
    lastActivityAtMs: h(1.5),
    turns: 10,
    usage: {
      input: 86_000,
      cacheRead: 3_900_000,
      cacheWrite: 430_000,
      output: 238_000,
      reasoning: 166_000,
    },
    delegated: [],
    faultNote:
      'Conformance run failed: vendor B’s adapter times out on holding-register reads at the bench. Likely the register map revision, not the suite — needs a human at the hardware.',
    readiness: 'live',
    tier: 'base',
    initiativeId: 'init-pilot-500',
  },

  /* ---------------- partner-portal ---------------- */
  {
    id: 'vg-por-calendar',
    name: 'Commissioning reminders',
    projectKey: 'partner-portal',
    goal: 'Build appointment reminders and homeowner confirmation for the installer scheduling calendar.',
    contextLabel: 'Sending reminder flow tests',
    status: 'working',
    source: 'codex',
    model: 'gpt-5.3-codex',
    effort: 'medium',
    gitBranch: null,
    roadmapItemId: 'POR-11',
    link: 'declared',
    startedAtMs: h(2.5),
    lastActivityAtMs: m(12),
    turns: 8,
    usage: {
      input: 64_000,
      cacheRead: 2_900_000,
      cacheWrite: 330_000,
      output: 172_000,
      reasoning: 121_000,
    },
    delegated: [],
    readiness: 'live',
    tier: 'base',
    initiativeId: 'init-pilot-500',
  },
  {
    id: 'vg-por-sso',
    name: 'Utility SSO integration',
    projectKey: 'partner-portal',
    goal: 'Integrate SAML SSO for the utility program team using their identity provider.',
    contextLabel: 'Waiting on IdP metadata',
    status: 'blocked',
    source: 'claude-code',
    model: 'claude-sonnet-5',
    effort: 'medium',
    gitBranch: 'agent/por-12-utility-sso',
    roadmapItemId: 'POR-12',
    link: 'declared',
    startedAtMs: d(1.2),
    lastActivityAtMs: h(4),
    turns: 6,
    usage: {
      input: 42_000,
      cacheRead: 1_900_000,
      cacheWrite: 220_000,
      output: 66_000,
      webSearches: 3,
    },
    delegated: [],
    blocker: {
      type: 'credentials_needed',
      title: 'SAML IdP metadata still missing from the utility’s IT team',
      description:
        'Requested 2026-07-22, chased twice. Integration is stubbed against a test IdP; nothing further ships without the production metadata XML.',
      suggestedResponses: ['Chase again today', 'Escalate via program manager', 'Park until metadata arrives'],
      createdAtMs: h(4),
    },
    readiness: 'live',
    tier: 'base',
    initiativeId: 'init-pilot-500',
  },

  /* ---------------- platform-infra ---------------- */
  {
    id: 'vg-inf-evidence',
    name: 'Restore-drill evidence capture',
    projectKey: 'platform-infra',
    goal: 'Automate backup-restore drill capture into the auditor evidence store with immutable timestamps.',
    contextLabel: 'Capturing tonight’s restore drill',
    status: 'working',
    source: 'claude-code',
    model: 'claude-opus-5',
    effort: 'high',
    gitBranch: 'agent/inf-21-restore-capture',
    roadmapItemId: 'INF-21',
    link: 'declared',
    startedAtMs: h(3),
    lastActivityAtMs: m(7),
    turns: 12,
    usage: {
      input: 188_000,
      cacheRead: 14_600_000,
      cacheWrite: 1_410_000,
      output: 241_000,
    },
    delegated: [
      {
        agentId: 'agent-c7f0',
        agentType: 'Explore',
        model: 'claude-sonnet-5',
        task: 'Inventory restore-drill log sources',
        startedAtMs: h(2.6),
        usage: { input: 58_000, cacheRead: 2_000_000, cacheWrite: 210_000, output: 79_000 },
      },
      {
        agentId: 'agent-c7f9',
        agentType: 'general-purpose',
        model: 'claude-opus-5',
        task: 'Immutable timestamp attestation path',
        startedAtMs: h(1.4),
        usage: { input: 44_000, cacheRead: 1_500_000, cacheWrite: 180_000, output: 68_000 },
      },
    ],
    readiness: 'live',
    tier: 'base',
    initiativeId: 'init-soc2',
  },
  {
    id: 'vg-inf-pg17',
    name: 'Postgres 17 rehearsal',
    projectKey: 'platform-infra',
    goal: 'Rehearse the Postgres 17 upgrade on a production clone and measure the dispatch write-path pause.',
    contextLabel: 'Rehearsal clean, 38s pause',
    status: 'complete',
    source: 'codex',
    model: 'gpt-5.3-codex',
    effort: 'high',
    gitBranch: null,
    roadmapItemId: 'INF-22',
    link: 'declared',
    startedAtMs: d(1.1),
    lastActivityAtMs: h(20),
    turns: 13,
    usage: {
      input: 142_000,
      cacheRead: 6_800_000,
      cacheWrite: 710_000,
      output: 388_000,
      reasoning: 274_000,
    },
    delegated: [],
    readiness: 'live',
    tier: 'base',
    initiativeId: 'init-soc2',
  },
  {
    id: 'vg-inf-spot',
    name: 'Spot bidder sketch',
    projectKey: 'platform-infra',
    goal: 'Sketch moving batch and simulation workloads to spot capacity with checkpointed resume.',
    contextLabel: 'Sketch parked for audit week',
    status: 'idle',
    source: 'codex',
    model: 'gpt-5.3-codex-mini',
    effort: 'low',
    gitBranch: null,
    roadmapItemId: 'INF-23',
    link: 'declared',
    startedAtMs: d(2.4),
    lastActivityAtMs: d(2.2),
    turns: 3,
    usage: {
      input: 16_000,
      cacheRead: 720_000,
      cacheWrite: 90_000,
      output: 44_000,
      reasoning: 29_000,
    },
    delegated: [],
    readiness: 'live',
    tier: 'base',
    initiativeId: null,
  },

  /* ---------------- market-intel (research, preview) ---------------- */
  {
    id: 'vg-res-nprr',
    name: 'NPRR impact briefs',
    projectKey: 'market-intel',
    goal: 'Draft impact briefs for the three open storage-relevant NPRR filings, each citing the filing text.',
    contextLabel: 'Drafting brief two of three',
    status: 'working',
    source: 'claude-code',
    model: 'claude-opus-5',
    effort: 'high',
    gitBranch: null,
    roadmapItemId: 'RES-7',
    link: 'declared',
    startedAtMs: h(4),
    lastActivityAtMs: m(15),
    turns: 9,
    usage: {
      input: 96_000,
      cacheRead: 5_800_000,
      cacheWrite: 620_000,
      output: 158_000,
      webSearches: 14,
    },
    delegated: [],
    readiness: 'preview',
    tier: 'base',
    initiativeId: 'init-ercot',
  },
  {
    id: 'vg-res-queue',
    name: 'Queue digest prep',
    projectKey: 'market-intel',
    goal: 'Assemble the interconnection queue snapshot ahead of the RES-8 digest work.',
    contextLabel: 'Queued behind NPRR briefs',
    status: 'idle',
    source: 'claude-code',
    model: 'claude-sonnet-5',
    effort: 'medium',
    gitBranch: null,
    roadmapItemId: 'RES-8',
    link: 'declared',
    startedAtMs: d(1.6),
    lastActivityAtMs: d(1.3),
    turns: 4,
    usage: {
      input: 28_000,
      cacheRead: 1_300_000,
      cacheWrite: 150_000,
      output: 39_000,
      webSearches: 8,
    },
    delegated: [],
    readiness: 'preview',
    tier: 'base',
    initiativeId: 'init-ercot',
  },

  /* ---------------- demand-gen (marketing, preview) ---------------- */
  {
    id: 'vg-mkt-launch',
    name: 'Launch narrative draft three',
    projectKey: 'demand-gen',
    goal: 'Produce draft three of the GA launch story across landing page, launch post, and press one-pager.',
    contextLabel: 'Draft three in claims audit',
    status: 'reviewing',
    source: 'claude-code',
    model: 'claude-opus-5',
    effort: 'high',
    gitBranch: null,
    roadmapItemId: 'MKT-9',
    link: 'declared',
    startedAtMs: h(21),
    lastActivityAtMs: h(2),
    turns: 10,
    usage: {
      input: 84_000,
      cacheRead: 4_700_000,
      cacheWrite: 520_000,
      output: 132_000,
      webSearches: 6,
    },
    delegated: [],
    readiness: 'preview',
    tier: 'base',
    initiativeId: 'init-home-ga',
  },
  {
    id: 'vg-mkt-comarketing',
    name: 'Co-marketing kit outline',
    projectKey: 'demand-gen',
    goal: 'Outline the installer co-marketing kit: kitchen-table one-pager, savings examples, and brand assets.',
    contextLabel: 'Outline waiting on launch copy',
    status: 'idle',
    source: 'claude-code',
    model: 'claude-sonnet-5',
    effort: 'medium',
    gitBranch: null,
    roadmapItemId: 'MKT-10',
    link: 'declared',
    startedAtMs: d(2.8),
    lastActivityAtMs: d(2.5),
    turns: 3,
    usage: {
      input: 19_000,
      cacheRead: 860_000,
      cacheWrite: 100_000,
      output: 27_000,
    },
    delegated: [],
    readiness: 'preview',
    tier: 'base',
    initiativeId: 'init-home-ga',
  },

  /* ---------------- support-ops (support, preview) ---------------- */
  {
    id: 'vg-sup-triage',
    name: 'Symptom taxonomy routing',
    projectKey: 'support-ops',
    goal: 'Classify the trailing 90 days of tickets into the symptom taxonomy and draft the routing rules.',
    contextLabel: 'Classifying week nine of thirteen',
    status: 'working',
    source: 'claude-code',
    model: 'claude-sonnet-5',
    effort: 'medium',
    gitBranch: null,
    roadmapItemId: 'SUP-5',
    link: 'declared',
    startedAtMs: h(5),
    lastActivityAtMs: m(18),
    turns: 11,
    usage: {
      input: 108_000,
      cacheRead: 6_100_000,
      cacheWrite: 660_000,
      output: 149_000,
    },
    delegated: [],
    readiness: 'preview',
    tier: 'base',
    initiativeId: 'init-pilot-500',
  },
  {
    id: 'vg-sup-digest',
    name: 'Escalation digest pilot',
    projectKey: 'support-ops',
    goal: 'Assemble the first daily escalation digest from this week’s escalated tickets with full context.',
    contextLabel: 'First digest ready to read',
    status: 'complete',
    source: 'claude-code',
    model: 'claude-sonnet-5',
    effort: 'medium',
    gitBranch: null,
    roadmapItemId: 'SUP-6',
    link: 'declared',
    startedAtMs: h(9),
    lastActivityAtMs: h(6),
    turns: 6,
    usage: {
      input: 38_000,
      cacheRead: 1_700_000,
      cacheWrite: 200_000,
      output: 52_000,
    },
    delegated: [],
    readiness: 'preview',
    tier: 'base',
    initiativeId: 'init-pilot-500',
  },
]);
