/* AUTO-GENERATED by scripts/generate-agent-source-declarations.mjs.
 * Edit contracts/agent-sources.json, then run pnpm agent-sources:generate. */
import type {
  AgentSourceAdapterId,
  AgentSourceCatalogEntry,
  AgentSourceDeclaration,
} from '@exawatt/core';

export const AGENT_SOURCE_DECLARATIONS = [
  {
    adapterId: 'claude',
    harness: 'claude',
    label: 'Claude Code',
    connectionName: 'Local CLI',
    color: '#DD896F',
    installationGuideUrl:
      'https://docs.anthropic.com/en/docs/claude-code/getting-started',
    description: 'Use the locally installed Claude Code CLI.',
    capabilities: {
      interactiveLaunch: true,
      initialTask: true,
      exactResume: true,
      modelSelection: 'live-catalog',
      effortSelection: 'live-catalog',
      permissionModes: ['prompt', 'auto', 'unrestricted'],
      delegationObservation: 'Source-reported lifecycle events',
      enforcementOwner: 'Claude Code',
    },
  },
  {
    adapterId: 'codex',
    harness: 'codex',
    label: 'Codex',
    connectionName: 'Local CLI',
    color: '#ECECEC',
    installationGuideUrl:
      'https://github.com/openai/codex#installing-and-running-codex-cli',
    description: 'Use the locally installed Codex CLI.',
    capabilities: {
      interactiveLaunch: true,
      initialTask: true,
      exactResume: true,
      modelSelection: 'live-catalog',
      effortSelection: 'live-catalog',
      permissionModes: ['prompt', 'auto', 'unrestricted'],
      delegationObservation: 'Codex does not report delegated work',
      enforcementOwner: 'Codex',
    },
  },
  {
    adapterId: 'opencode',
    harness: 'opencode',
    label: 'OpenCode',
    connectionName: 'Local CLI',
    color: '#FAB283',
    installationGuideUrl: 'https://opencode.ai/docs',
    description: 'Use the locally installed multi-provider OpenCode CLI.',
    capabilities: {
      interactiveLaunch: true,
      initialTask: true,
      exactResume: true,
      modelSelection: 'live-catalog',
      effortSelection: 'live-catalog',
      permissionModes: ['prompt', 'auto', 'unrestricted'],
      delegationObservation: 'OpenCode PTY does not report delegated work',
      enforcementOwner: 'OpenCode',
    },
  },
  {
    adapterId: 'openclaw',
    harness: null,
    label: 'OpenClaw',
    connectionName: 'Local gateway',
    color: '#8BB9ED',
    installationGuideUrl: 'https://docs.openclaw.ai/install',
    description: 'Connect a local OpenClaw gateway.',
    capabilities: {
      interactiveLaunch: false,
      initialTask: true,
      exactResume: true,
      modelSelection: 'gateway',
      effortSelection: 'gateway',
      permissionModes: [],
      delegationObservation: 'Gateway protocol events',
      enforcementOwner: 'OpenClaw gateway',
    },
  },
  {
    adapterId: 'demo',
    harness: null,
    label: 'Demo Mode',
    connectionName: 'Scenario source',
    color: '#E7BD6A',
    installationGuideUrl: null,
    description: 'Built-in source with clearly simulated provenance.',
    capabilities: {
      interactiveLaunch: false,
      initialTask: true,
      exactResume: true,
      modelSelection: 'scenario',
      effortSelection: 'scenario',
      permissionModes: [],
      delegationObservation: 'Simulated lifecycle events',
      enforcementOwner: 'No real enforcement (simulation)',
    },
  },
] as const satisfies readonly AgentSourceDeclaration[];

export const FUTURE_AGENT_SOURCE_CATALOG = [
  {
    adapterId: 'hosted-openclaw',
    label: 'Hosted OpenClaw',
    description: 'Connect a remote or managed gateway.',
    availability: 'coming-soon',
  },
  {
    adapterId: 'custom',
    label: 'Custom harness',
    description: 'Bring another compatible Agent Source adapter.',
    availability: 'coming-soon',
  },
] as const satisfies readonly AgentSourceCatalogEntry[];

export function agentSourceDeclaration(
  adapterId: AgentSourceAdapterId
): AgentSourceDeclaration {
  const declaration = AGENT_SOURCE_DECLARATIONS.find(
    candidate => candidate.adapterId === adapterId
  );
  if (!declaration) throw new Error(`Unknown Agent Source: ${adapterId}`);
  return declaration;
}
